### ISSUE TITLE
kube-apiserver (1.0.6) error (reflector.go)

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#171]
I see some errors on master after the installation on windows:

```
core@master ~ $  systemctl -l status kube-apiserver -n100
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2015-10-09 20:50:55 UTC; 2min 34s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 1714 ExecStartPre=/opt/bin/wupiao 172.17.8.101:2379/v2/machines (code=exited, status=0/SUCCESS)
 Main PID: 1716 (kube-apiserver)
   Memory: 25.2M
      CPU: 628ms
   CGroup: /system.slice/kube-apiserver.service
           └─1716 /opt/bin/kube-apiserver --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --service_account_key_file=/srv/kubernetes/server.key --service_account_lookup=false --allow_privileged=true --insecure_bind_address=0.0.0.0 --insecure_port=8080 --kubelet_https=true --secure_port=6443 --service-cluster-ip-range=10.100.0.0/16 --etcd_servers=http://172.17.8.101:2379 --bind-address=172.17.8.101 --cloud_provider= --logtostderr=true --runtime_config=api/v1

Oct 09 20:50:55 master systemd[1]: Starting Kubernetes API Server...
Oct 09 20:50:55 master systemd[1]: Started Kubernetes API Server.
Oct 09 20:50:55 master kube-apiserver[1716]: I1009 20:50:55.392519    1716 plugins.go:69] No cloud provider specified.
Oct 09 20:50:55 master kube-apiserver[1716]: I1009 20:50:55.527953    1716 master.go:273] Node port range unspecified. Defaulting to 30000-32767.
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.548720    1716 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8080/api/v1/resourcequotas: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.549767    1716 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.550064    1716 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8080/api/v1/serviceaccounts: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.550350    1716 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8080/api/v1/limitranges: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.550655    1716 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8080/api/v1/namespaces: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: E1009 20:50:55.550899    1716 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8080/api/v1/namespaces: dial tcp 0.0.0.0:8080: connection refused
Oct 09 20:50:55 master kube-apiserver[1716]: [restful] 2015/10/09 20:50:55 log.go:30: [restful/swagger] listing is available at https://172.17.8.101:6443/swaggerapi/
Oct 09 20:50:55 master kube-apiserver[1716]: [restful] 2015/10/09 20:50:55 log.go:30: [restful/swagger] https://172.17.8.101:6443/swaggerui/ is mapped to folder /swagger-ui/
Oct 09 20:50:55 master kube-apiserver[1716]: W1009 20:50:55.603822    1716 controller.go:212] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default    0 0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{172.17.8.101 <nil>}] [{ 6443 TCP}]}]}
Oct 09 20:50:55 master kube-apiserver[1716]: I1009 20:50:55.619777    1716 server.go:441] Serving securely on 172.17.8.101:6443
Oct 09 20:50:55 master kube-apiserver[1716]: I1009 20:50:55.619778    1716 server.go:483] Serving insecurely on 0.0.0.0:8080


core@master ~ $ curl 127.0.0.1:8080
{
  "paths": [
    "/api",
    "/api/v1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```

**Comment by pires** [comment]
I'll probably revert Windows support. This is not something I can debug and/or fix.

**Comment by remoe** [comment]
I'm not sure if this only a windows issue. I found some in the kubernetes repos. Please don't remove windows support. :)

**Comment by pires** [comment]
Never had this error before. Unless it's something very specific to 1.0.6 but still it shouldn't be an error!

**Comment by remoe** [comment]
I don't have an error on master-console when I try to get this resources:

```
core@master ~ $ curl http://0.0.0.0:8080/api/v1/resourcequotas
{
  "kind": "ResourceQuotaList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/resourcequotas",
    "resourceVersion": "549"
  },
  "items": []
}core@master ~ $ cat http://0.0.0.0:8080/api/v1/namespaces
cat: http://0.0.0.0:8080/api/v1/namespaces: No such file or directory
core@master ~ $ curl http://0.0.0.0:8080/api/v1/serviceaccounts
{
  "kind": "ServiceAccountList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/serviceaccounts",
    "resourceVersion": "603"
  },
  "items": [
    {
      "metadata": {
        "name": "default",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/serviceaccounts/default",
        "uid": "53986ce1-6f26-11e5-aa3b-080027ebc558",
        "resourceVersion": "41",
        "creationTimestamp": "2015-10-10T08:10:10Z"
      },
      "secrets": [
        {
          "name": "default-token-3b0d5"
        }
      ]
    }
  ]
}core@master ~ $
```

**Comment by remoe** [comment]
Found?:
https://github.com/kubernetes/kubernetes/issues/12715

"harmless" :)

**Comment by pires** [comment]
Thank you for taking the time to let us know.

**Comment by aeoluswing** [comment]
Is this issue still followed?We suffer the same phenomenon in v1.3:
`[root@kube-master kubernetes]# systemctl status kube-apiserver.service  -l                                                                          ● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-07-27 10:10:59 CST; 15min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 10775 (kube-apiserver)
   Memory: 36.9M
   CGroup: /system.slice/kube-apiserver.service
           └─10775 /usr/bin/kube-apiserver --logtostderr=true --v=0 --log-dir=/var/log/kubernetes --insecure-bind-address=0.0.0.0 --insecure-port=8080 --secure-port=6443 --etcd-servers=http://kube-master:2379 --allow-privileged=false --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --client-ca-file=/var/run/kubernetes/ca.crt --tls-private-key-file=/var/run/kubernetes/server.key --tls-cert-file=/var/run/kubernetes/server.crt

Jul 27 10:10:59 kube-master kube-apiserver[10775]: E0727 10:10:59.715041   10775 reflector.go:216] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get http://0.0.0.0:8080/api/v1/serviceaccounts?resourceVersion=0: dial tcp 0.0.0.0:8080: getsockopt: connection refused
Jul 27 10:10:59 kube-master kube-apiserver[10775]: E0727 10:10:59.715447   10775 reflector.go:216] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://0.0.0.0:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 0.0.0.0:8080: getsockopt: connection refused
Jul 27 10:10:59 kube-master kube-apiserver[10775]: E0727 10:10:59.715522   10775 reflector.go:205] k8s.io/kubernetes/plugin/pkg/admission/resourcequota/controller.go:121: Failed to list *api.ResourceQuota: Get http://0.0.0.0:8080/api/v1/resourcequotas?resourceVersion=0: dial tcp 0.0.0.0:8080: getsockopt: connection refused
Jul 27 10:10:59 kube-master kube-apiserver[10775]: E0727 10:10:59.715564   10775 reflector.go:205] k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission.go:116: Failed to list *api.Namespace: Get http://0.0.0.0:8080/api/v1/namespaces?resourceVersion=0: dial tcp 0.0.0.0:8080: getsockopt: connection refused
`
and by the way,`curl` from port 8080 works fine:
`[root@kube-master kubernetes]# curl http://0.0.0.0:8080/
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1alpha1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1alpha1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]`

**Comment by pires** [comment]
It's harmless.
