### ISSUE TITLE
kubectlsetup is not uploaded to VM

### ISSUE THREAD

**Issue by teestone** [pires/kubernetes-vagrant-coreos-cluster#199]
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Sanitizing stuff...
==> master: Waiting for Kubernetes master to become ready...
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master: /bin/sh: /home/core/kubectlsetup: No such file or directory
==> master: Remote command execution finished.
The remote command "sudo -u core /bin/sh /home/core/kubectlsetup install" returned a failed exit
code or an exception. The error output is shown below:

/bin/sh: /home/core/kubectlsetup: No such file or directory

**Comment by BitBldr** [comment]
I am seeing this issue as well. The short term fix I have used is to delete ~/.vagrant.d every time you run vagrant up. I believe it has to do with the code path which installs kubectlsetup in the Vagrant file not being executed if you have already previously provisioned these VMs

**Comment by pires** [comment]
I am **again** tempted to just ditch Windows support since I don't use such OS nor have I found anyone willing to help maintain it.

**Comment by BitBldr** [comment]
I've seen this on both Windows and OS X

**Comment by pires** [comment]
@BitBldr `setup` runs on host machine so I'm not sure what you're talking about.

**Comment by BitBldr** [comment]
Yeah, you're right. I forgot to mention I had modified the vagrant file to install kubectlsetup on all OS types, simply because I liked having it run the same on all my machines. I understand you can't account for modifications, but all I was saying was its not because of Windows this issue is occurring, it seems to be because of the way the vagrant file installs the kubectlsetup after you have already created and destroyed the cluster (which just so happens to be a Windows only code path)

I would be sad to see Windows support be lost on this. While Windiws isn't my main OS, I would like to help maintain it for Windows users, however I have struggled to figure this one out myself (being that I am not a vagrant/ruby guru). I'll give it another look

**Comment by pires** [comment]
@BitBldr good luck, I hope you figure it out and I'm eager to review your PRs.

**Comment by pires** [comment]
Fixed.
