### ISSUE TITLE
Single-node cluster if num-instances set to 1?

### ISSUE THREAD

**Issue by sandric** [pires/kubernetes-vagrant-coreos-cluster#86]
It would be a handy feature to set up single-node cluster with user-data similar to one from https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_single_node_cluster.md
How do you think?

**Comment by pires** [comment]
From the top of my mind it would implicate a lot of refactoring of the Vagrantfile. I'm open to review a PR.

**Comment by sandric** [comment]
Ok, I'll try my best)

**Comment by AntonioMeireles** [comment]
one note - right now NUM_INSTANCES=1 creates two VMs - one for master and another for node-01. (setting it to 0 would just create master)

**Comment by tdeheurles** [comment]
In order to run the project on one node (the master), you need :
- pass NUM_INSTANCES to 0
- Certainly add some memory with MASTER_MEM
- move `kube-proxy.service` and `kube-kubelet.service` from node.yaml to master.yaml
- add the following code under the [unit] section of `kube-proxy.service` and `kube-kubelet.service`
```
Requires=kube-apiserver.service kube-controller-manager.service kube-scheduler.service
After=kube-apiserver.service kube-controller-manager.service kube-scheduler.serviceand
```

I need this to run this (in order to have local docker registry directly running) and so I will probably need to fork. But maybe we can add that feature to this project.
The main problem is to cleanly add the two services to the master when needed.

**Comment by pires** [comment]
Just a side-note, single node cluster is an anti-pattern and has been deprecated upstream, at least in the CoreOS docs.

**Comment by tdeheurles** [comment]
So maybe CoreOS is not a good target for simple local kubernetes test.
My idea was to not work on too much stuff (as CoreOS seems pretty good when cluster is needed)

Thanks for response

**Comment by pires** [comment]
Check @kelseyhightower scripts for running it on top of Docker.

**Comment by tdeheurles** [comment]
Thanks for the link, lots of good stuff in it.

But many people are using Windows and I'm stuck with a VM for now, that's one of the reason I go in your project.

If someone still need that project on only one node, they can look [here](https://github.com/tdeheurles/HomeKube)

**Comment by pires** [comment]
Why a single VM?

**Comment by tdeheurles** [comment]
I'm looking for the easiest way to run a local kubernetes for team (local test / plane situation / etc).
The team is working on Windows.

The problem of multi VM is with docker registry.
- With one VM, I can build inside the master (there is docker), and run `kubectl create` (because the built image is in docker daemon => no need for registry).
- With cluster, nodes are looking for images in their docker daemon (it's was build in the master, so the images is not in the node), and it seems that I need to setup a docker registry.

**Comment by pires** [comment]
OK, it's a peculiar scenario. If you're able to provide a PR that enables this without breaking current behavior, I'm glad to review it and possibly merge it. Thank you for you feedback @tdeheurles

**Comment by pires** [comment]
Stalled.

**Comment by tdeheurles** [comment]
Sorry, forget to close that one.

As we talk in some other post, I don't think the design of this project will be good with the subject of this post.
**kubernetes-vagrant-coreos-cluster** seems perfect for `entering kubernetes world` and adding complexity seems a bad idea.

I started a project named [homecores](https://github.com/tdeheurles/homecores) that try to go in that post way.
