### ISSUE TITLE
Disable VirtualBox DHCP server

### ISSUE THREAD

**Issue by wstrange** [pires/kubernetes-vagrant-coreos-cluster#87]
Why is this required, and will it impact other VirtualBox VMs?

Can you add a note on this

**Comment by pires** [comment]
This is highly recommended because otherwise you may have issues with Kubernetes cluster networking. Many users reported good clusters going awry and after some time debugging we realized it was caused by Virtualbox DHCP changing VMs IP addresses.

Yes, this will most probably have impact on other VMs that rely on the same NIC we've disabled DHCP server.

Probably, this will no longer have impact because we now have a very strict VM IP addressing, but I need more feedback before removing that one from documentation.

**Comment by wstrange** [comment]
OK - I found that the cluster would not come up with DHCP enabled. DNS resolution on the minion seemed broken.  I dont know enough about coreos, but it seems like the host only network should be configured to ignore the external DNS and hard wire the IP.

**Comment by pires** [comment]
I'm open to review a PR :)
